# Test the order-service

### Place an order
POST https://order--service-b6fcckbwfphpgpb8.canadacentral-01.azurewebsites.net/orders
Content-Type: application/json

{
  "product": "Cat Food",
  "price": "59.99$"
}
